version: '{build}'
os: Visual Studio 2019

environment:
  PGUSER: postgres
  PGPASSWORD: Password12!
  ACCESS_TOKEN:
    secure: g1T332Uarmdgtkftchpafa8tDP/7eM4O0BD6iu1wu+zR224IyH5R8pb4sTChr4Ia

# REF: https://github.com/docascode/docfx-seed/blob/master/appveyor.yml
before_build:
  - ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
        {
            git checkout $env:APPVEYOR_REPO_BRANCH -q
            choco install docfx -y
        }

after_build:
  - ps: |
        CD ./docs
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
        {
            & docfx docfx.json
            if ($lastexitcode -ne 0){
              throw [System.Exception] "docfx build failed with exit code $lastexitcode."
            }
            
            git config --global credential.helper store
            Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:ACCESS_TOKEN):x-oauth-basic@github.com`n"
            git config --global user.email "jaredcnance@gmail.com"
            git config --global user.name "Jared Nance"
            git config --global core.autocrlf false
            git config --global core.safecrlf false
            git clone https://github.com/json-api-dotnet/JsonApiDotNetCore.git -b gh-pages origin_site -q
            Copy-Item origin_site/.git _site -recurse
            CD _site
            git add -A 2>&1
            git commit -m "CI Updates" -q
            git push origin gh-pages -q
            echo "Documentation updated successfully."
        }

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master
  - develop
  - unstable
  - /release\/.+/

nuget:
  disable_publish_on_pr: true

init:
  - SET PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%

services:  
  - postgresql96

build_script:
- ps: dotnet --version
- ps: .\Build.ps1

test: off

artifacts:
- path: .\**\artifacts\**\*.nupkg
  name: NuGet

deploy:
- provider: NuGet
  server: https://www.myget.org/F/research-institute/api/v2/package
  api_key:
    secure: 6CeYcZ4Ze+57gxfeuHzqP6ldbUkPtF6pfpVM1Gw/K2jExFrAz763gNAQ++tiacq3
  skip_symbols: false
  symbol_server: https://www.myget.org/F/research-institute/symbols/api/v2/package
  on:
    branch: develop

- provider: NuGet
  server: https://www.myget.org/F/jadnc/api/v2/package
  api_key:
    secure: 6CeYcZ4Ze+57gxfeuHzqP6ldbUkPtF6pfpVM1Gw/K2jExFrAz763gNAQ++tiacq3
  skip_symbols: false
  on:
    branch: unstable

- provider: NuGet
  name: production
  skip_symbols: false
  api_key:
    secure: /fsEOgG4EdtNd6DPmko9h3NxQwx1IGDcFreGTKd2KA56U2KEkpX/L/pCGpCIEf2s
  on:
    branch: master
    appveyor_repo_tag: true

- provider: NuGet
  skip_symbols: false
  api_key:
    secure: /fsEOgG4EdtNd6DPmko9h3NxQwx1IGDcFreGTKd2KA56U2KEkpX/L/pCGpCIEf2s
  on:
    branch: /release\/.+/
    appveyor_repo_tag: true
